word_list = ["aardvark", "baboon", "camel","python",
        "hangman",
        "computer",
        "programming",
        "algorithm",
        "code",
        "openai",
        "language",
        "model",
        "intelligence",
        "game",
        "random",
        "guess",
        "challenge",
        "fun"]